name: Sellio CI

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.92.0
          components: rustfmt, clippy

      - name: Cargo check (server)
        run: cargo check --manifest-path server/Cargo.toml

      - name: Rustfmt (server)
        run: cargo fmt --manifest-path server/Cargo.toml -- --check

      - name: Clippy (server)
        run: cargo clippy --manifest-path server/Cargo.toml -- -D warnings

      - name: Build (release, server)
        run: cargo build --manifest-path server/Cargo.toml --release

      - name: Test (server)
        run: cargo test --manifest-path server/Cargo.toml --verbose

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.92.0
          components: rustfmt, clippy

      - name: Cargo check (server)
        run: cargo check --manifest-path server/Cargo.toml

      - name: Rustfmt (server)
        run: cargo fmt --manifest-path server/Cargo.toml -- --check

      - name: Clippy (server)
        run: cargo clippy --manifest-path server/Cargo.toml -- -D warnings

      - name: Build (release, server)
        run: cargo build --manifest-path server/Cargo.toml --release

      - name: Test (server)
        run: cargo test --manifest-path server/Cargo.toml --verbose
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.92.0
          components: rustfmt, clippy

      - name: Cargo check (server)
        run: cargo check --manifest-path server/Cargo.toml

      - name: Rustfmt (server)
        run: cargo fmt --manifest-path server/Cargo.toml -- --check

      - name: Clippy (server)
        run: cargo clippy --manifest-path server/Cargo.toml -- -D warnings

      - name: Build (release, server)
        run: cargo build --manifest-path server/Cargo.toml --release

      - name: Test (server)
        run: cargo test --manifest-path server/Cargo.toml --verbose